version: "3.8"

services:
  mysql-server:
    image: mysql
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
