debug: false

logging:
  level:
    com.example.CatalogService: debug
    org.springframework.web.servlet: debug
    org.springframework.security: debug

#server:
#  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true
    url: "jdbc:mysql://mysql-server:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: 1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #jpa batch query 사이즈
        default_batch_fetch_size: 100
        use_sql_comments: true

  cassandra:
    keyspace-name: catalog
    port: 9042
    contact-points: cassandra-node-0
    local-datacenter: dc1
    schema-action: create-if-not-exists

  kafka:
    bootstrap-servers:
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092
    consumer:
      group-id: testgroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
