debug: false

logging:
  level:
    com.example.SearchService: debug
    org.springframework.web.servlet: debug
    org.springframework.security: debug

server:
  port: 8084
---

spring:
  config:
    activate:
      on-profile: test
