debug: false

logging:
  level:
    com.example.SearchService: debug
    org.springframework.web.servlet: debug
    org.springframework.security: debug

spring:
  data:
    redis:
      host: redis-server
      port: 6379
#server:
#  port: 8084
---

spring:
  config:
    activate:
      on-profile: test
